### ISSUE TITLE
Layout limitations

### ISSUE THREAD

**Issue by filoxo** [msvisser/AnnePro-mac#6]
Hey there, just noticed some behavior on the layout editor and wanted to verify its validity. Is there a reason why a key can only be assigned once? For example, I find that the FN key is placed poorly, so I want the default RSHIFT key to instead be FN, but when I attempt to do so, the layout editor unassigns the old FN key. I feel like it shouldn't do that since one might want multiple keys to do that same thing. 

Is this a limitation of the keyboard firmware, or of this application? Thanks in advance!

**Comment by msvisser** [comment]
Because of the firmware limitations you can only have one key assigned to FN and ANNE. You are also required to have a FN and ANNE key in your layout, and they should be on the same key in both the normal and FN layer. These constraints are enforced by the program, although they are not clearly documented, and there is no error reporting right now.

**Comment by filoxo** [comment]
Great to know! Thanks for the information! Closing this issue then.
